"""
Matterport3D npy → OBJ 변환기
사용법: python npy_to_obj.py --data_dir ./scene_folder --output scene.obj
"""

import numpy as np
import argparse
import os
from scipy.spatial import Delaunay


def load_npy_files(data_dir):
    """4개 npy 파일 로드"""
    coord  = np.load(os.path.join(data_dir, "coord.npy"))   # (N, 3) XYZ
    color  = np.load(os.path.join(data_dir, "color.npy"))   # (N, 3) RGB 0~255
    normal = np.load(os.path.join(data_dir, "normal.npy"))  # (N, 3) 법선벡터
    segment = np.load(os.path.join(data_dir, "segment.npy")) # (N,)  세그먼트 ID

    print(f"[로드 완료]")
    print(f"  coord  : {coord.shape}")
    print(f"  color  : {color.shape}")
    print(f"  normal : {normal.shape}")
    print(f"  segment: {segment.shape}")
    return coord, color, normal, segment


def normalize_colors(color):
    """색상 0~255 → 0.0~1.0"""
    if color.max() > 1.0:
        return color.astype(float) / 255.0
    return color.astype(float)


def build_faces_by_segment(coord, segment, max_points_per_seg=5000):
    """
    세그먼트별로 Delaunay 삼각분할로 면(face) 생성.
    포인트가 너무 많은 세그먼트는 샘플링.
    """
    faces = []
    unique_segs = np.unique(segment)
    total = len(unique_segs)

    print(f"[삼각분할] 세그먼트 수: {total}")

    for i, seg_id in enumerate(unique_segs):
        idx = np.where(segment == seg_id)[0]

        # 너무 많으면 샘플링
        if len(idx) > max_points_per_seg:
            idx = np.random.choice(idx, max_points_per_seg, replace=False)

        pts = coord[idx]

        if len(pts) < 3:
            continue

        # 세그먼트의 주축(PCA)에 투영해서 2D Delaunay
        try:
            centered = pts - pts.mean(axis=0)
            _, _, Vt = np.linalg.svd(centered, full_matrices=False)
            proj = centered @ Vt[:2].T  # 2D 투영

            tri = Delaunay(proj)
            for simplex in tri.simplices:
                # 1-indexed OBJ face (전역 인덱스로 변환)
                faces.append((idx[simplex[0]] + 1,
                               idx[simplex[1]] + 1,
                               idx[simplex[2]] + 1))
        except Exception:
            continue

        if (i + 1) % 100 == 0:
            print(f"  {i+1}/{total} 처리 중...")

    print(f"[삼각분할 완료] 생성된 면: {len(faces)}개")
    return faces


def write_mtl(mtl_path, color, faces_with_color=False):
    """
    MTL 파일 작성 — 버텍스 컬러 방식은 OBJ에 직접 포함되므로
    여기서는 기본 material만 작성
    """
    with open(mtl_path, "w") as f:
        f.write("# MTL generated by npy_to_obj.py\n")
        f.write("newmtl default\n")
        f.write("Ka 1.0 1.0 1.0\n")
        f.write("Kd 1.0 1.0 1.0\n")
        f.write("Ks 0.0 0.0 0.0\n")
        f.write("illum 1\n")


def write_obj(output_path, coord, color, normal, faces):
    """OBJ 파일 작성 (버텍스 컬러 포함)"""
    mtl_name = os.path.splitext(os.path.basename(output_path))[0] + ".mtl"
    mtl_path = os.path.join(os.path.dirname(output_path), mtl_name)

    color_f = normalize_colors(color)

    print(f"[OBJ 작성 중] → {output_path}")

    with open(output_path, "w") as f:
        f.write("# OBJ converted from Matterport3D npy\n")
        f.write(f"# Vertices: {len(coord)}, Faces: {len(faces)}\n")
        f.write(f"mtllib {mtl_name}\n")
        f.write("usemtl default\n\n")

        # 버텍스 (v x y z r g b — Blender/MeshLab 확장 포맷)
        for i, (xyz, rgb) in enumerate(zip(coord, color_f)):
            f.write(f"v {xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f} "
                    f"{rgb[0]:.6f} {rgb[1]:.6f} {rgb[2]:.6f}\n")

        # 법선벡터
        for n in normal:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")

        f.write("\n")

        # 면 (f v1//vn1 v2//vn2 v3//vn3)
        for face in faces:
            a, b, c = face
            f.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")

    write_mtl(mtl_path, color_f)
    print(f"[완료] OBJ: {output_path}")
    print(f"[완료] MTL: {mtl_path}")


def pointcloud_only_obj(output_path, coord, color, normal):
    """
    면 없이 포인트클라우드만 OBJ로 저장 (가장 빠름, Unity에서 점으로 보임)
    삼각분할이 너무 오래 걸릴 때 사용
    """
    mtl_name = os.path.splitext(os.path.basename(output_path))[0] + ".mtl"
    mtl_path = os.path.join(os.path.dirname(output_path), mtl_name)
    color_f = normalize_colors(color)

    print(f"[포인트클라우드 OBJ 작성 중] → {output_path}")

    with open(output_path, "w") as f:
        f.write("# OBJ (point cloud only) from Matterport3D npy\n")
        f.write(f"mtllib {mtl_name}\n")
        f.write("usemtl default\n\n")

        for xyz, rgb in zip(coord, color_f):
            f.write(f"v {xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f} "
                    f"{rgb[0]:.6f} {rgb[1]:.6f} {rgb[2]:.6f}\n")

        for n in normal:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")

    write_mtl(mtl_path, color_f)
    print(f"[완료] 포인트클라우드 OBJ: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Matterport3D npy → OBJ 변환")
    parser.add_argument("--data_dir", required=True,
                        help="coord.npy, color.npy, normal.npy, segment.npy가 있는 폴더")
    parser.add_argument("--output", default="output.obj",
                        help="출력 OBJ 파일 경로 (기본값: output.obj)")
    parser.add_argument("--mode", choices=["mesh", "pointcloud"], default="mesh",
                        help="mesh: 삼각분할 포함 / pointcloud: 버텍스만 (빠름)")
    parser.add_argument("--max_pts", type=int, default=5000,
                        help="세그먼트 최대 포인트 수 (기본값: 5000)")
    args = parser.parse_args()

    # 출력 디렉토리 생성
    out_dir = os.path.dirname(args.output)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir)

    # 로드
    coord, color, normal, segment = load_npy_files(args.data_dir)

    if args.mode == "pointcloud":
        pointcloud_only_obj(args.output, coord, color, normal)
    else:
        faces = build_faces_by_segment(coord, segment, max_points_per_seg=args.max_pts)
        write_obj(args.output, coord, color, normal, faces)

    print("\n[Unity 임포트 팁]")
    print("  1. Assets 폴더에 .obj + .mtl 같이 넣기")
    print("  2. OBJ 임포트 설정 → Read/Write 체크")
    print("  3. 버텍스 컬러는 Shader Graph에서 'Vertex Color' 노드로 연결")


if __name__ == "__main__":
    main()